name: "Wire Generate"
description: "Generate Wire file for a directory"
inputs:
  directory: # id of input
    description: "Directory to run Wire on"
    required: true
outputs: {}
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.directory }}
branding:
  icon: 'activity'
  color: 'purple'
